apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-master-data-1
spec:
  storageClassName: hadoop-master-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/hadoop/data/master/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-a
              - ap-south-1a
              - zone-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-slave-data-1
spec:
  storageClassName: hadoop-slave-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/hadoop/data/slave/1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-b
              - ap-south-1b
              - zone-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-slave-data-2
spec:
  storageClassName: hadoop-slave-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/hadoop/data/slave/2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-b
              - ap-south-1b
              - zone-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-slave-data-3
spec:
  storageClassName: hadoop-slave-data
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubernetes/hadoop/data/slave/3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-b
              - ap-south-1b
              - zone-2