# Cookbook attributes.
default['system']['user'] = 'ec2-user'
default['system']['group'] = 'ec2-user'
default['system']['kernel']['vm.swappiness'] = 0
default['system']['kernel']['vm.overcommit_memory'] = 1
default['system']['kernel']['vm.max_map_count'] = 262144
default['system']['kernel']['net.core.somaxconn'] = 65536
default['system']['kernel']['net.ipv4.tcp_max_syn_backlog'] = 8192
default['system']['kernel']['net.bridge.bridge-nf-call-ip6tables'] = 1
default['system']['kernel']['net.ipv4.ip_forward'] = 1
default['system']['kernel']['net.bridge.bridge-nf-call-iptables'] = 1
