apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sloopstash-ctm-mongo-db-data-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sloopstash-ctm-mongo-db-log-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
