apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-log
spec:
  storageClassName: sloopstash-${ENVIRONMENT}-crm-app-log
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
