apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log
spec:
  storageClassName: sloopstash-${ENVIRONMENT}-crm-nginx-log
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
