apiVersion: v1
kind: PersistentVolume
metadata:
  name: sloopstash-${ENVIRONMENT}-ollama-qwen-2-5-coder-0-model
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/sloopstash/${ENVIRONMENT}/ollama/qwen-2.5-coder/0/model
  claimRef:
    namespace: sloopstash-${ENVIRONMENT}-ai-s1
    name: ollama-qwen-2-5-coder-model-qwen-2-5-coder-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-c
              - ap-south-1a
              - zone-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sloopstash-${ENVIRONMENT}-ollama-qwen-2-5-coder-0-data
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/sloopstash/${ENVIRONMENT}/ollama/qwen-2.5-coder/0/data
  claimRef:
    namespace: sloopstash-${ENVIRONMENT}-ai-s1
    name: ollama-qwen-2-5-coder-data-qwen-2-5-coder-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-c
              - ap-south-1a
              - zone-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sloopstash-${ENVIRONMENT}-ollama-qwen-2-5-coder-0-log
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/sloopstash/${ENVIRONMENT}/ollama/qwen-2.5-coder/0/log
  claimRef:
    namespace: sloopstash-${ENVIRONMENT}-ai-s1
    name: ollama-qwen-2-5-coder-log-qwen-2-5-coder-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
              - cloud
          - key: provider
            operator: In
            values:
              - host
              - aws
              - azure
          - key: service
            operator: In
            values:
              - virtualbox
              - ec2
              - eks
              - aks
          - key: region
            operator: In
            values:
              - local
              - ap-south-1
              - centralindia
          - key: availability_zone
            operator: In
            values:
              - local-c
              - ap-south-1a
              - zone-1
