apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
spec:
  selector:
    matchLabels:
      service: kafka-broker
  replicas: 3
  serviceName: kafka-broker
  template:
    metadata:
      labels:
        service: kafka-broker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - on-premise
                    - cloud
                - key: provider
                  operator: In
                  values:
                    - host
                    - aws
                    - azure
                - key: service
                  operator: In
                  values:
                    - virtualbox
                    - ec2
                    - eks
                    - aks
                - key: region
                  operator: In
                  values:
                    - local
                    - ap-south-1
                    - centralindia
                - key: availability_zone
                  operator: In
                  values:
                    - local-c
                    - ap-south-1b
                    - zone-2
      containers:
        - name: main
          image: sloopstash/kafka:v${DATA_LAKE_KAFKA_VERSION}
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/supervisord"]
          args: ["-c", "/etc/supervisord.conf"]
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
          volumeMounts:
            - name: kafka-data
              mountPath: /opt/kafka/data
            - name: kafka-log
              mountPath: /opt/kafka/log
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: kafka-supervisor
              mountPath: /opt/kafka/system/supervisor.ini
              subPath: supervisor.ini
            - name: kafka-server
              mountPath: /opt/kafka/conf/server-reference.conf
              subPath: server.conf
            - name: kafka-start
              mountPath: /opt/kafka/script/start.sh
              subPath: start.sh
            - name: kafka-stop
              mountPath: /opt/kafka/script/stop.sh
              subPath: stop.sh
          ports:
            - containerPort: 9092
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
        - name: kafka-log
          persistentVolumeClaim:
            claimName: kafka-log
        - name: supervisor-server
          configMap:
            name: kafka-broker
        - name: kafka-supervisor
          configMap:
            name: kafka-broker
            items:
              - key: supervisor.ini
                path: supervisor.ini
        - name: kafka-server
          configMap:
            name: kafka-broker
            items:
              - key: server.conf
                path: server.conf
        - name: kafka-start
          configMap:
            name: kafka-broker
            defaultMode: 0755
            items:
              - key: start.sh
                path: start.sh
        - name: kafka-stop
          configMap:
            name: kafka-broker
            defaultMode: 0755
            items:
              - key: stop.sh
                path: stop.sh
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: kafka-log
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
