apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      service: redis
  replicas: 1
  serviceName: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - on-premise
                    - cloud
                - key: provider
                  operator: In
                  values:
                    - host
                    - aws
                    - azure
                - key: service
                  operator: In
                  values:
                    - virtualbox
                    - ec2
                    - eks
                    - aks
                - key: region
                  operator: In
                  values:
                    - local
                    - ap-south-1
                    - centralindia
                - key: availability_zone
                  operator: In
                  values:
                    - local-b
                    - ap-south-1b
                    - zone-2
      containers:
        - name: main
          image: sloopstash/redis:v4.0.9
          imagePullPolicy: Always
          command: ["/usr/bin/supervisord"]
          args: ["-c", "/etc/supervisord.conf"]
          volumeMounts:
            - name: redis-data
              mountPath: /opt/redis/data
            - name: redis-log
              mountPath: /opt/redis/log
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: redis-supervisor
              mountPath: /opt/redis/system/supervisor.ini
              subPath: redis-supervisor
            - name: redis-server
              mountPath: /opt/redis/conf/server.conf
              subPath: redis-server
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command:
                - "/usr/local/bin/redis-cli"
                - "-p"
                - "3000"
                - "PING"
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: log
          image: sloopstash/redis:v4.0.9
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/supervisord"]
          args: ["-c", "/etc/supervisord.conf"]
          volumeMounts:
            - name: redis-log
              mountPath: /opt/redis/log
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-log
          persistentVolumeClaim:
            claimName: redis-log
        - name: supervisor-server
          configMap:
            name: redis
        - name: redis-supervisor
          configMap:
            name: redis
        - name: redis-server
          configMap:
            name: redis
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: sloopstash-${ENVIRONMENT}-crm-redis-data
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: redis-log
      spec:
        storageClassName: sloopstash-${ENVIRONMENT}-crm-redis-log
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
