apiVersion: v1
kind: Service
metadata:
  name: kafka-controller
  labels:
    service: kafka-controller
spec:
  ports:
    - name: listner
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    service: kafka-controller
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    service: kafka-broker
spec:
  ports:
    - name: listner
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    service: kafka-broker
