apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    service: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: ${CTM_NGINX_PORT}
      targetPort: 80
      protocol: TCP
  selector:
    service: nginx