# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "sloopstash/centos-7"
  config.vm.box_version = "1.1.1"

  # Define virtual machine name.
  # config.vm.define "sloopstash-centos-7-server"

  # Set virtual machine hostname.
  # config.vm.hostname = "sloopstash-centos-7-server"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 443, host: 443, auto_correct: false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.101.4"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # SSH credentials to connect to virtual machine.
  config.ssh.username = "vagrant"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Enable USB controller for the virtual machine.
    vb.customize ["modifyvm",:id,"--usb","on"]

    # Disable GUI when booting the virtual machine.
    vb.gui = false
  
    # Allocate memory to the virtual machine.
    vb.memory = "2048"

    # Allocate processors to the virtual machine.
    vb.cpus = "2"

    # Set name for the virtual machine.
    # vb.name = "sloopstash-centos-7-server"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    systemctl stop postfix.service
    systemctl disable postfix.service
    yum update -y
    yum install -y wget vim nano net-tools initscripts gcc make tar bind-utils nc git unzip sysstat tree
  SHELL

  # Define multiple virtual machines.
  config.vm.define "sloopstash-k8s-mtr-1" do |sloopstash_k8s_mtr_1|
    sloopstash_k8s_mtr_1.vm.hostname = "sloopstash-k8s-mtr-1"
    sloopstash_k8s_mtr_1.vm.network "private_network", ip: "192.168.101.61"
    sloopstash_k8s_mtr_1.vm.provider "virtualbox" do |vb|
      vb.name = "sloopstash-k8s-mtr-1"
    end
  end
  config.vm.define "sloopstash-k8s-wkr-1" do |sloopstash_k8s_wkr_1|
    sloopstash_k8s_wkr_1.vm.hostname = "sloopstash-k8s-wkr-1"
    sloopstash_k8s_wkr_1.vm.network "private_network", ip: "192.168.101.64"
    sloopstash_k8s_wkr_1.vm.provider "virtualbox" do |vb|
      vb.name = "sloopstash-k8s-wkr-1"
    end
    sloopstash_k8s_wkr_1.vm.provision "shell", inline: <<-SHELL
      mkdir -p /mnt/sloopstash/qaa/crm/redis/data
      mkdir -p /mnt/sloopstash/qaa/crm/redis/log
      mkdir -p /mnt/sloopstash/qaa/crm/app/log
      mkdir -p /mnt/sloopstash/qaa/crm/nginx/log
      mkdir -p /mnt/sloopstash/qab/crm/redis/data
      mkdir -p /mnt/sloopstash/qab/crm/redis/log
      mkdir -p /mnt/sloopstash/qab/crm/app/log
      mkdir -p /mnt/sloopstash/qab/crm/nginx/log
      mkdir -p /mnt/sloopstash/stg/crm/redis/data
      mkdir -p /mnt/sloopstash/stg/crm/redis/log
      mkdir -p /mnt/sloopstash/stg/crm/app/log
      mkdir -p /mnt/sloopstash/stg/crm/nginx/log
      mkdir -p /mnt/sloopstash/prd/crm/redis/data
      mkdir -p /mnt/sloopstash/prd/crm/redis/log
      mkdir -p /mnt/sloopstash/prd/crm/app/log
      mkdir -p /mnt/sloopstash/prd/crm/nginx/log
      chmod -R ugo+rwx /mnt/sloopstash
    SHELL
  end
  config.vm.define "sloopstash-k8s-wkr-2" do |sloopstash_k8s_wkr_2|
    sloopstash_k8s_wkr_2.vm.hostname = "sloopstash-k8s-wkr-2"
    sloopstash_k8s_wkr_2.vm.network "private_network", ip: "192.168.101.65"
    sloopstash_k8s_wkr_2.vm.provider "virtualbox" do |vb|
      vb.name = "sloopstash-k8s-wkr-2"
    end
    sloopstash_k8s_wkr_2.vm.provision "shell", inline: <<-SHELL
      mkdir -p /mnt/sloopstash/qaa/crm/redis/data
      mkdir -p /mnt/sloopstash/qaa/crm/redis/log
      mkdir -p /mnt/sloopstash/qaa/crm/app/log
      mkdir -p /mnt/sloopstash/qaa/crm/nginx/log
      mkdir -p /mnt/sloopstash/qab/crm/redis/data
      mkdir -p /mnt/sloopstash/qab/crm/redis/log
      mkdir -p /mnt/sloopstash/qab/crm/app/log
      mkdir -p /mnt/sloopstash/qab/crm/nginx/log
      mkdir -p /mnt/sloopstash/stg/crm/redis/data
      mkdir -p /mnt/sloopstash/stg/crm/redis/log
      mkdir -p /mnt/sloopstash/stg/crm/app/log
      mkdir -p /mnt/sloopstash/stg/crm/nginx/log
      mkdir -p /mnt/sloopstash/prd/crm/redis/data
      mkdir -p /mnt/sloopstash/prd/crm/redis/log
      mkdir -p /mnt/sloopstash/prd/crm/app/log
      mkdir -p /mnt/sloopstash/prd/crm/nginx/log
      chmod -R ugo+rwx /mnt/sloopstash
    SHELL
  end
end
